- name: Install Docker on Ubuntu nodes
  hosts: node-ubuntu
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: common/gather-facts
      tags:
        - common::os
    # - import_role:
    #     name: windows/run-test
    #   tags:
    #     - windows::requirements
    #     - windows::docker
    #     - windows::test

    # - import_role:
    #     name: windows/cni
    #   tags:
    #     - windows::requirements
    # - import_role:
    #     name: windows/kubernetes-node
    #   tags:
    #     - windows::requirements
    #     - windows::node
    # - import_role:
    #     name: windows/flannel
    #   when: kube_network_plugin == 'flannel'
    #   tags:
    #     - windows::flannel
