- name: Install mssql on Linux nodes
  hosts: node-ubuntu
  environment: "{{ env_vars|default({}) }}"
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: linux/mssql
      tags:
        - linux::mssql
