- name: Install Docker on windows nodes
  hosts: node-windows
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:
    - import_role:
        name: windows/version
      tags:
        - windows::version
    - import_role:
        name: windows/iis
      tags:
        - windows::iis
    #     - windows::docker
    #     - windows::test

    # - import_role:
    #     name: windows/cni
    #   tags:
    #     - windows::requirements
    # - import_role:
    #     name: windows/kubernetes-node
    #   tags:
    #     - windows::requirements
    #     - windows::node
    # - import_role:
    #     name: windows/flannel
    #   when: kube_network_plugin == 'flannel'
    #   tags:
    #     - windows::flannel
